### PR TITLE
Per-node version and status in cluster_info view, minor aesthetic changes (css).

### PR DESCRIPTION
**Pull request by wildstray**

### CODE REVIEW

**Comment by sebgiroux** [comment]
Sweet!

Few things: I'm not sure about the green/red background, probably a Up (green)/Down(red) beside the server's IP would be enough. Also I couldn't get the node down to display at all. When the node is down, it just doesn't appear in the list for me for some reason. And please try to keep the code style (ex: use "" in HTML attribute so it's valid).

Let me know what do you think of this :)

**Comment by wildstray** [comment]
...sorry, maybe I got over enthusiastic with colors xD I'll modify it as you suggested. About the unreachable server, can you var_dump your $schema_version?

**Comment by sebgiroux** [comment]
The unreachable server is not in $schema_version at all, I'm not sure why :/ If you add a random IP in the nodes list config, you still see it as down in your schema version list ?

**Comment by wildstray** [comment]
$schema_version reports only valid nodes of the cluster with version for nodes running and UNREACHABLE for nodes donw. Random ip address aren't reported in the schema versions list.

**Pull request merged**
